### ISSUE TITLE
Typo in lesson 14 chapter 2

### ISSUE THREAD

**Issue by gtupak** [loomnetwork/cryptozombie-lessons#465]
In https://cryptozombies.io/en/lesson/14/chapter/2, it says “The first line of code should set oracleAddress to _address” but it should probably say “The first line of code should set oracleAddress to _oracleInstanceAddress”

**Comment by conroywhitney** [comment]
This is fixed in #481

**Comment by patr1cketh** [comment]
![image](https://user-images.githubusercontent.com/87179170/126313301-daf9ed44-788f-4b34-a3cd-f945706e7eaf.png)
This still isn't fixed for me
